name: Label based on PR size

on:
  workflow_dispatch:
  pull_request_target:
    types: [opened, reopened, synchronize]
jobs:
  size-label:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      statuses: write
      pull-requests: write

    steps:

      - name: size-label
        uses: "pascalgn/size-label-action@v0.5.5"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
